spring.application.name=trilhossp

# H2 R2DBC
spring.r2dbc.url=r2dbc:h2:mem:///trilhossp;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.r2dbc.username=sa
spring.r2dbc.password=
spring.sql.init.mode=always

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# ARTESP API
artesp.api.base-url=https://ccm.artesp.sp.gov.br/metroferroviario/api/status/
artesp.api.key=${ARTESP_API_KEY:}

# CPTM API
cptm.api.base-url=https://api.cptm.sp.gov.br/AppCPTM/v1/Linhas/ObterStatus

# Metrô SP API
metro.api.base-url=https://www.metro.sp.gov.br/wp-content/themes/metrosp/direto-metro.php

# Grupo CCR API
ccr.api.base-url=https://webapi.grupoccr.com.br/v1/mobility/public/line-status/current/state/SP

# Notifications
notify.days=${NOTIFY_DAYS:all}
notify.level=${NOTIFY_LEVEL:0}
notify.lines=${NOTIFY_LINES:all}

# Gotify
gotify.url=${GOTIFY_URL:}
gotify.token=${GOTIFY_TOKEN:}
